/*
 * This file is generated by jOOQ.
 */
package model.information_schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRoutineGrants implements Serializable {

    private static final long serialVersionUID = 1L;

    private String grantor;
    private String grantee;
    private String specificCatalog;
    private String specificSchema;
    private String specificName;
    private String routineCatalog;
    private String routineSchema;
    private String routineName;
    private String privilegeType;
    private String isGrantable;

    public RoleRoutineGrants() {}

    public RoleRoutineGrants(RoleRoutineGrants value) {
        this.grantor = value.grantor;
        this.grantee = value.grantee;
        this.specificCatalog = value.specificCatalog;
        this.specificSchema = value.specificSchema;
        this.specificName = value.specificName;
        this.routineCatalog = value.routineCatalog;
        this.routineSchema = value.routineSchema;
        this.routineName = value.routineName;
        this.privilegeType = value.privilegeType;
        this.isGrantable = value.isGrantable;
    }

    public RoleRoutineGrants(
        String grantor,
        String grantee,
        String specificCatalog,
        String specificSchema,
        String specificName,
        String routineCatalog,
        String routineSchema,
        String routineName,
        String privilegeType,
        String isGrantable
    ) {
        this.grantor = grantor;
        this.grantee = grantee;
        this.specificCatalog = specificCatalog;
        this.specificSchema = specificSchema;
        this.specificName = specificName;
        this.routineCatalog = routineCatalog;
        this.routineSchema = routineSchema;
        this.routineName = routineName;
        this.privilegeType = privilegeType;
        this.isGrantable = isGrantable;
    }

    /**
     * Getter for <code>information_schema.role_routine_grants.grantor</code>.
     */
    public String getGrantor() {
        return this.grantor;
    }

    /**
     * Setter for <code>information_schema.role_routine_grants.grantor</code>.
     */
    public void setGrantor(String grantor) {
        this.grantor = grantor;
    }

    /**
     * Getter for <code>information_schema.role_routine_grants.grantee</code>.
     */
    public String getGrantee() {
        return this.grantee;
    }

    /**
     * Setter for <code>information_schema.role_routine_grants.grantee</code>.
     */
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.specific_catalog</code>.
     */
    public String getSpecificCatalog() {
        return this.specificCatalog;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.specific_catalog</code>.
     */
    public void setSpecificCatalog(String specificCatalog) {
        this.specificCatalog = specificCatalog;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.specific_schema</code>.
     */
    public String getSpecificSchema() {
        return this.specificSchema;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.specific_schema</code>.
     */
    public void setSpecificSchema(String specificSchema) {
        this.specificSchema = specificSchema;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.specific_name</code>.
     */
    public String getSpecificName() {
        return this.specificName;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.specific_name</code>.
     */
    public void setSpecificName(String specificName) {
        this.specificName = specificName;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.routine_catalog</code>.
     */
    public String getRoutineCatalog() {
        return this.routineCatalog;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.routine_catalog</code>.
     */
    public void setRoutineCatalog(String routineCatalog) {
        this.routineCatalog = routineCatalog;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.routine_schema</code>.
     */
    public String getRoutineSchema() {
        return this.routineSchema;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.routine_schema</code>.
     */
    public void setRoutineSchema(String routineSchema) {
        this.routineSchema = routineSchema;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.routine_name</code>.
     */
    public String getRoutineName() {
        return this.routineName;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.routine_name</code>.
     */
    public void setRoutineName(String routineName) {
        this.routineName = routineName;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.privilege_type</code>.
     */
    public String getPrivilegeType() {
        return this.privilegeType;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.privilege_type</code>.
     */
    public void setPrivilegeType(String privilegeType) {
        this.privilegeType = privilegeType;
    }

    /**
     * Getter for
     * <code>information_schema.role_routine_grants.is_grantable</code>.
     */
    public String getIsGrantable() {
        return this.isGrantable;
    }

    /**
     * Setter for
     * <code>information_schema.role_routine_grants.is_grantable</code>.
     */
    public void setIsGrantable(String isGrantable) {
        this.isGrantable = isGrantable;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RoleRoutineGrants other = (RoleRoutineGrants) obj;
        if (this.grantor == null) {
            if (other.grantor != null)
                return false;
        }
        else if (!this.grantor.equals(other.grantor))
            return false;
        if (this.grantee == null) {
            if (other.grantee != null)
                return false;
        }
        else if (!this.grantee.equals(other.grantee))
            return false;
        if (this.specificCatalog == null) {
            if (other.specificCatalog != null)
                return false;
        }
        else if (!this.specificCatalog.equals(other.specificCatalog))
            return false;
        if (this.specificSchema == null) {
            if (other.specificSchema != null)
                return false;
        }
        else if (!this.specificSchema.equals(other.specificSchema))
            return false;
        if (this.specificName == null) {
            if (other.specificName != null)
                return false;
        }
        else if (!this.specificName.equals(other.specificName))
            return false;
        if (this.routineCatalog == null) {
            if (other.routineCatalog != null)
                return false;
        }
        else if (!this.routineCatalog.equals(other.routineCatalog))
            return false;
        if (this.routineSchema == null) {
            if (other.routineSchema != null)
                return false;
        }
        else if (!this.routineSchema.equals(other.routineSchema))
            return false;
        if (this.routineName == null) {
            if (other.routineName != null)
                return false;
        }
        else if (!this.routineName.equals(other.routineName))
            return false;
        if (this.privilegeType == null) {
            if (other.privilegeType != null)
                return false;
        }
        else if (!this.privilegeType.equals(other.privilegeType))
            return false;
        if (this.isGrantable == null) {
            if (other.isGrantable != null)
                return false;
        }
        else if (!this.isGrantable.equals(other.isGrantable))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.grantor == null) ? 0 : this.grantor.hashCode());
        result = prime * result + ((this.grantee == null) ? 0 : this.grantee.hashCode());
        result = prime * result + ((this.specificCatalog == null) ? 0 : this.specificCatalog.hashCode());
        result = prime * result + ((this.specificSchema == null) ? 0 : this.specificSchema.hashCode());
        result = prime * result + ((this.specificName == null) ? 0 : this.specificName.hashCode());
        result = prime * result + ((this.routineCatalog == null) ? 0 : this.routineCatalog.hashCode());
        result = prime * result + ((this.routineSchema == null) ? 0 : this.routineSchema.hashCode());
        result = prime * result + ((this.routineName == null) ? 0 : this.routineName.hashCode());
        result = prime * result + ((this.privilegeType == null) ? 0 : this.privilegeType.hashCode());
        result = prime * result + ((this.isGrantable == null) ? 0 : this.isGrantable.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoleRoutineGrants (");

        sb.append(grantor);
        sb.append(", ").append(grantee);
        sb.append(", ").append(specificCatalog);
        sb.append(", ").append(specificSchema);
        sb.append(", ").append(specificName);
        sb.append(", ").append(routineCatalog);
        sb.append(", ").append(routineSchema);
        sb.append(", ").append(routineName);
        sb.append(", ").append(privilegeType);
        sb.append(", ").append(isGrantable);

        sb.append(")");
        return sb.toString();
    }
}
