/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonbArrayElements implements Serializable {

    private static final long serialVersionUID = 1L;

    private JSONB value;

    public JsonbArrayElements() {}

    public JsonbArrayElements(JsonbArrayElements value) {
        this.value = value.value;
    }

    public JsonbArrayElements(
        JSONB value
    ) {
        this.value = value;
    }

    /**
     * Getter for <code>pg_catalog.jsonb_array_elements.value</code>.
     */
    public JSONB getValue() {
        return this.value;
    }

    /**
     * Setter for <code>pg_catalog.jsonb_array_elements.value</code>.
     */
    public void setValue(JSONB value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JsonbArrayElements other = (JsonbArrayElements) obj;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JsonbArrayElements (");

        sb.append(value);

        sb.append(")");
        return sb.toString();
    }
}
