/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonArrayElementsText implements Serializable {

    private static final long serialVersionUID = 1L;

    private String value;

    public JsonArrayElementsText() {}

    public JsonArrayElementsText(JsonArrayElementsText value) {
        this.value = value.value;
    }

    public JsonArrayElementsText(
        String value
    ) {
        this.value = value;
    }

    /**
     * Getter for <code>pg_catalog.json_array_elements_text.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>pg_catalog.json_array_elements_text.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JsonArrayElementsText other = (JsonArrayElementsText) obj;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JsonArrayElementsText (");

        sb.append(value);

        sb.append(")");
        return sb.toString();
    }
}
