/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonbEachText implements Serializable {

    private static final long serialVersionUID = 1L;

    private String key;
    private String value;

    public JsonbEachText() {}

    public JsonbEachText(JsonbEachText value) {
        this.key = value.key;
        this.value = value.value;
    }

    public JsonbEachText(
        String key,
        String value
    ) {
        this.key = key;
        this.value = value;
    }

    /**
     * Getter for <code>pg_catalog.jsonb_each_text.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>pg_catalog.jsonb_each_text.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>pg_catalog.jsonb_each_text.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>pg_catalog.jsonb_each_text.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JsonbEachText other = (JsonbEachText) obj;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JsonbEachText (");

        sb.append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
