/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonbPathQueryTz implements Serializable {

    private static final long serialVersionUID = 1L;

    private JSONB jsonbPathQueryTz;

    public JsonbPathQueryTz() {}

    public JsonbPathQueryTz(JsonbPathQueryTz value) {
        this.jsonbPathQueryTz = value.jsonbPathQueryTz;
    }

    public JsonbPathQueryTz(
        JSONB jsonbPathQueryTz
    ) {
        this.jsonbPathQueryTz = jsonbPathQueryTz;
    }

    /**
     * Getter for
     * <code>pg_catalog.jsonb_path_query_tz.jsonb_path_query_tz</code>.
     */
    public JSONB getJsonbPathQueryTz() {
        return this.jsonbPathQueryTz;
    }

    /**
     * Setter for
     * <code>pg_catalog.jsonb_path_query_tz.jsonb_path_query_tz</code>.
     */
    public void setJsonbPathQueryTz(JSONB jsonbPathQueryTz) {
        this.jsonbPathQueryTz = jsonbPathQueryTz;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JsonbPathQueryTz other = (JsonbPathQueryTz) obj;
        if (this.jsonbPathQueryTz == null) {
            if (other.jsonbPathQueryTz != null)
                return false;
        }
        else if (!this.jsonbPathQueryTz.equals(other.jsonbPathQueryTz))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.jsonbPathQueryTz == null) ? 0 : this.jsonbPathQueryTz.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JsonbPathQueryTz (");

        sb.append(jsonbPathQueryTz);

        sb.append(")");
        return sb.toString();
    }
}
