/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgCast implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long oid;
    private Long castsource;
    private Long casttarget;
    private Long castfunc;
    private String castcontext;
    private String castmethod;

    public PgCast() {}

    public PgCast(PgCast value) {
        this.oid = value.oid;
        this.castsource = value.castsource;
        this.casttarget = value.casttarget;
        this.castfunc = value.castfunc;
        this.castcontext = value.castcontext;
        this.castmethod = value.castmethod;
    }

    public PgCast(
        Long oid,
        Long castsource,
        Long casttarget,
        Long castfunc,
        String castcontext,
        String castmethod
    ) {
        this.oid = oid;
        this.castsource = castsource;
        this.casttarget = casttarget;
        this.castfunc = castfunc;
        this.castcontext = castcontext;
        this.castmethod = castmethod;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.oid</code>.
     */
    public Long getOid() {
        return this.oid;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.oid</code>.
     */
    public void setOid(Long oid) {
        this.oid = oid;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.castsource</code>.
     */
    public Long getCastsource() {
        return this.castsource;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.castsource</code>.
     */
    public void setCastsource(Long castsource) {
        this.castsource = castsource;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.casttarget</code>.
     */
    public Long getCasttarget() {
        return this.casttarget;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.casttarget</code>.
     */
    public void setCasttarget(Long casttarget) {
        this.casttarget = casttarget;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.castfunc</code>.
     */
    public Long getCastfunc() {
        return this.castfunc;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.castfunc</code>.
     */
    public void setCastfunc(Long castfunc) {
        this.castfunc = castfunc;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.castcontext</code>.
     */
    public String getCastcontext() {
        return this.castcontext;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.castcontext</code>.
     */
    public void setCastcontext(String castcontext) {
        this.castcontext = castcontext;
    }

    /**
     * Getter for <code>pg_catalog.pg_cast.castmethod</code>.
     */
    public String getCastmethod() {
        return this.castmethod;
    }

    /**
     * Setter for <code>pg_catalog.pg_cast.castmethod</code>.
     */
    public void setCastmethod(String castmethod) {
        this.castmethod = castmethod;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgCast other = (PgCast) obj;
        if (this.oid == null) {
            if (other.oid != null)
                return false;
        }
        else if (!this.oid.equals(other.oid))
            return false;
        if (this.castsource == null) {
            if (other.castsource != null)
                return false;
        }
        else if (!this.castsource.equals(other.castsource))
            return false;
        if (this.casttarget == null) {
            if (other.casttarget != null)
                return false;
        }
        else if (!this.casttarget.equals(other.casttarget))
            return false;
        if (this.castfunc == null) {
            if (other.castfunc != null)
                return false;
        }
        else if (!this.castfunc.equals(other.castfunc))
            return false;
        if (this.castcontext == null) {
            if (other.castcontext != null)
                return false;
        }
        else if (!this.castcontext.equals(other.castcontext))
            return false;
        if (this.castmethod == null) {
            if (other.castmethod != null)
                return false;
        }
        else if (!this.castmethod.equals(other.castmethod))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.oid == null) ? 0 : this.oid.hashCode());
        result = prime * result + ((this.castsource == null) ? 0 : this.castsource.hashCode());
        result = prime * result + ((this.casttarget == null) ? 0 : this.casttarget.hashCode());
        result = prime * result + ((this.castfunc == null) ? 0 : this.castfunc.hashCode());
        result = prime * result + ((this.castcontext == null) ? 0 : this.castcontext.hashCode());
        result = prime * result + ((this.castmethod == null) ? 0 : this.castmethod.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgCast (");

        sb.append(oid);
        sb.append(", ").append(castsource);
        sb.append(", ").append(casttarget);
        sb.append(", ").append(castfunc);
        sb.append(", ").append(castcontext);
        sb.append(", ").append(castmethod);

        sb.append(")");
        return sb.toString();
    }
}
