/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDefaultAcl implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long oid;
    private Long defaclrole;
    private Long defaclnamespace;
    private String defaclobjtype;
    private String[] defaclacl;

    public PgDefaultAcl() {}

    public PgDefaultAcl(PgDefaultAcl value) {
        this.oid = value.oid;
        this.defaclrole = value.defaclrole;
        this.defaclnamespace = value.defaclnamespace;
        this.defaclobjtype = value.defaclobjtype;
        this.defaclacl = value.defaclacl;
    }

    public PgDefaultAcl(
        Long oid,
        Long defaclrole,
        Long defaclnamespace,
        String defaclobjtype,
        String[] defaclacl
    ) {
        this.oid = oid;
        this.defaclrole = defaclrole;
        this.defaclnamespace = defaclnamespace;
        this.defaclobjtype = defaclobjtype;
        this.defaclacl = defaclacl;
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.oid</code>.
     */
    public Long getOid() {
        return this.oid;
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.oid</code>.
     */
    public void setOid(Long oid) {
        this.oid = oid;
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclrole</code>.
     */
    public Long getDefaclrole() {
        return this.defaclrole;
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclrole</code>.
     */
    public void setDefaclrole(Long defaclrole) {
        this.defaclrole = defaclrole;
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclnamespace</code>.
     */
    public Long getDefaclnamespace() {
        return this.defaclnamespace;
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclnamespace</code>.
     */
    public void setDefaclnamespace(Long defaclnamespace) {
        this.defaclnamespace = defaclnamespace;
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclobjtype</code>.
     */
    public String getDefaclobjtype() {
        return this.defaclobjtype;
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclobjtype</code>.
     */
    public void setDefaclobjtype(String defaclobjtype) {
        this.defaclobjtype = defaclobjtype;
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclacl</code>.
     */
    public String[] getDefaclacl() {
        return this.defaclacl;
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclacl</code>.
     */
    public void setDefaclacl(String[] defaclacl) {
        this.defaclacl = defaclacl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgDefaultAcl other = (PgDefaultAcl) obj;
        if (this.oid == null) {
            if (other.oid != null)
                return false;
        }
        else if (!this.oid.equals(other.oid))
            return false;
        if (this.defaclrole == null) {
            if (other.defaclrole != null)
                return false;
        }
        else if (!this.defaclrole.equals(other.defaclrole))
            return false;
        if (this.defaclnamespace == null) {
            if (other.defaclnamespace != null)
                return false;
        }
        else if (!this.defaclnamespace.equals(other.defaclnamespace))
            return false;
        if (this.defaclobjtype == null) {
            if (other.defaclobjtype != null)
                return false;
        }
        else if (!this.defaclobjtype.equals(other.defaclobjtype))
            return false;
        if (this.defaclacl == null) {
            if (other.defaclacl != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.defaclacl, other.defaclacl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.oid == null) ? 0 : this.oid.hashCode());
        result = prime * result + ((this.defaclrole == null) ? 0 : this.defaclrole.hashCode());
        result = prime * result + ((this.defaclnamespace == null) ? 0 : this.defaclnamespace.hashCode());
        result = prime * result + ((this.defaclobjtype == null) ? 0 : this.defaclobjtype.hashCode());
        result = prime * result + ((this.defaclacl == null) ? 0 : Arrays.deepHashCode(this.defaclacl));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgDefaultAcl (");

        sb.append(oid);
        sb.append(", ").append(defaclrole);
        sb.append(", ").append(defaclnamespace);
        sb.append(", ").append(defaclobjtype);
        sb.append(", ").append(Arrays.deepToString(defaclacl));

        sb.append(")");
        return sb.toString();
    }
}
