/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgEventTriggerDdlCommands implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long classid;
    private Long objid;
    private Integer objsubid;
    private String commandTag;
    private String objectType;
    private String schemaName;
    private String objectIdentity;
    private Boolean inExtension;
    private Object command;

    public PgEventTriggerDdlCommands() {}

    public PgEventTriggerDdlCommands(PgEventTriggerDdlCommands value) {
        this.classid = value.classid;
        this.objid = value.objid;
        this.objsubid = value.objsubid;
        this.commandTag = value.commandTag;
        this.objectType = value.objectType;
        this.schemaName = value.schemaName;
        this.objectIdentity = value.objectIdentity;
        this.inExtension = value.inExtension;
        this.command = value.command;
    }

    public PgEventTriggerDdlCommands(
        Long classid,
        Long objid,
        Integer objsubid,
        String commandTag,
        String objectType,
        String schemaName,
        String objectIdentity,
        Boolean inExtension,
        Object command
    ) {
        this.classid = classid;
        this.objid = objid;
        this.objsubid = objsubid;
        this.commandTag = commandTag;
        this.objectType = objectType;
        this.schemaName = schemaName;
        this.objectIdentity = objectIdentity;
        this.inExtension = inExtension;
        this.command = command;
    }

    /**
     * Getter for <code>pg_catalog.pg_event_trigger_ddl_commands.classid</code>.
     */
    public Long getClassid() {
        return this.classid;
    }

    /**
     * Setter for <code>pg_catalog.pg_event_trigger_ddl_commands.classid</code>.
     */
    public void setClassid(Long classid) {
        this.classid = classid;
    }

    /**
     * Getter for <code>pg_catalog.pg_event_trigger_ddl_commands.objid</code>.
     */
    public Long getObjid() {
        return this.objid;
    }

    /**
     * Setter for <code>pg_catalog.pg_event_trigger_ddl_commands.objid</code>.
     */
    public void setObjid(Long objid) {
        this.objid = objid;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.objsubid</code>.
     */
    public Integer getObjsubid() {
        return this.objsubid;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.objsubid</code>.
     */
    public void setObjsubid(Integer objsubid) {
        this.objsubid = objsubid;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.command_tag</code>.
     */
    public String getCommandTag() {
        return this.commandTag;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.command_tag</code>.
     */
    public void setCommandTag(String commandTag) {
        this.commandTag = commandTag;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.object_type</code>.
     */
    public String getObjectType() {
        return this.objectType;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.object_type</code>.
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.schema_name</code>.
     */
    public String getSchemaName() {
        return this.schemaName;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.schema_name</code>.
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.object_identity</code>.
     */
    public String getObjectIdentity() {
        return this.objectIdentity;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.object_identity</code>.
     */
    public void setObjectIdentity(String objectIdentity) {
        this.objectIdentity = objectIdentity;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.in_extension</code>.
     */
    public Boolean getInExtension() {
        return this.inExtension;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_ddl_commands.in_extension</code>.
     */
    public void setInExtension(Boolean inExtension) {
        this.inExtension = inExtension;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getCommand() {
        return this.command;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setCommand(Object command) {
        this.command = command;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgEventTriggerDdlCommands other = (PgEventTriggerDdlCommands) obj;
        if (this.classid == null) {
            if (other.classid != null)
                return false;
        }
        else if (!this.classid.equals(other.classid))
            return false;
        if (this.objid == null) {
            if (other.objid != null)
                return false;
        }
        else if (!this.objid.equals(other.objid))
            return false;
        if (this.objsubid == null) {
            if (other.objsubid != null)
                return false;
        }
        else if (!this.objsubid.equals(other.objsubid))
            return false;
        if (this.commandTag == null) {
            if (other.commandTag != null)
                return false;
        }
        else if (!this.commandTag.equals(other.commandTag))
            return false;
        if (this.objectType == null) {
            if (other.objectType != null)
                return false;
        }
        else if (!this.objectType.equals(other.objectType))
            return false;
        if (this.schemaName == null) {
            if (other.schemaName != null)
                return false;
        }
        else if (!this.schemaName.equals(other.schemaName))
            return false;
        if (this.objectIdentity == null) {
            if (other.objectIdentity != null)
                return false;
        }
        else if (!this.objectIdentity.equals(other.objectIdentity))
            return false;
        if (this.inExtension == null) {
            if (other.inExtension != null)
                return false;
        }
        else if (!this.inExtension.equals(other.inExtension))
            return false;
        if (this.command == null) {
            if (other.command != null)
                return false;
        }
        else if (!this.command.equals(other.command))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.classid == null) ? 0 : this.classid.hashCode());
        result = prime * result + ((this.objid == null) ? 0 : this.objid.hashCode());
        result = prime * result + ((this.objsubid == null) ? 0 : this.objsubid.hashCode());
        result = prime * result + ((this.commandTag == null) ? 0 : this.commandTag.hashCode());
        result = prime * result + ((this.objectType == null) ? 0 : this.objectType.hashCode());
        result = prime * result + ((this.schemaName == null) ? 0 : this.schemaName.hashCode());
        result = prime * result + ((this.objectIdentity == null) ? 0 : this.objectIdentity.hashCode());
        result = prime * result + ((this.inExtension == null) ? 0 : this.inExtension.hashCode());
        result = prime * result + ((this.command == null) ? 0 : this.command.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgEventTriggerDdlCommands (");

        sb.append(classid);
        sb.append(", ").append(objid);
        sb.append(", ").append(objsubid);
        sb.append(", ").append(commandTag);
        sb.append(", ").append(objectType);
        sb.append(", ").append(schemaName);
        sb.append(", ").append(objectIdentity);
        sb.append(", ").append(inExtension);
        sb.append(", ").append(command);

        sb.append(")");
        return sb.toString();
    }
}
