/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetMultixactMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long xid;
    private String mode;

    public PgGetMultixactMembers() {}

    public PgGetMultixactMembers(PgGetMultixactMembers value) {
        this.xid = value.xid;
        this.mode = value.mode;
    }

    public PgGetMultixactMembers(
        Long xid,
        String mode
    ) {
        this.xid = xid;
        this.mode = mode;
    }

    /**
     * Getter for <code>pg_catalog.pg_get_multixact_members.xid</code>.
     */
    public Long getXid() {
        return this.xid;
    }

    /**
     * Setter for <code>pg_catalog.pg_get_multixact_members.xid</code>.
     */
    public void setXid(Long xid) {
        this.xid = xid;
    }

    /**
     * Getter for <code>pg_catalog.pg_get_multixact_members.mode</code>.
     */
    public String getMode() {
        return this.mode;
    }

    /**
     * Setter for <code>pg_catalog.pg_get_multixact_members.mode</code>.
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgGetMultixactMembers other = (PgGetMultixactMembers) obj;
        if (this.xid == null) {
            if (other.xid != null)
                return false;
        }
        else if (!this.xid.equals(other.xid))
            return false;
        if (this.mode == null) {
            if (other.mode != null)
                return false;
        }
        else if (!this.mode.equals(other.mode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.xid == null) ? 0 : this.xid.hashCode());
        result = prime * result + ((this.mode == null) ? 0 : this.mode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgGetMultixactMembers (");

        sb.append(xid);
        sb.append(", ").append(mode);

        sb.append(")");
        return sb.toString();
    }
}
