/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPartitionedTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long partrelid;
    private String partstrat;
    private Short partnatts;
    private Long partdefid;
    private Object[] partattrs;
    private Object[] partclass;
    private Object[] partcollation;
    private Object partexprs;

    public PgPartitionedTable() {}

    public PgPartitionedTable(PgPartitionedTable value) {
        this.partrelid = value.partrelid;
        this.partstrat = value.partstrat;
        this.partnatts = value.partnatts;
        this.partdefid = value.partdefid;
        this.partattrs = value.partattrs;
        this.partclass = value.partclass;
        this.partcollation = value.partcollation;
        this.partexprs = value.partexprs;
    }

    public PgPartitionedTable(
        Long partrelid,
        String partstrat,
        Short partnatts,
        Long partdefid,
        Object[] partattrs,
        Object[] partclass,
        Object[] partcollation,
        Object partexprs
    ) {
        this.partrelid = partrelid;
        this.partstrat = partstrat;
        this.partnatts = partnatts;
        this.partdefid = partdefid;
        this.partattrs = partattrs;
        this.partclass = partclass;
        this.partcollation = partcollation;
        this.partexprs = partexprs;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partrelid</code>.
     */
    public Long getPartrelid() {
        return this.partrelid;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partrelid</code>.
     */
    public void setPartrelid(Long partrelid) {
        this.partrelid = partrelid;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partstrat</code>.
     */
    public String getPartstrat() {
        return this.partstrat;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partstrat</code>.
     */
    public void setPartstrat(String partstrat) {
        this.partstrat = partstrat;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partnatts</code>.
     */
    public Short getPartnatts() {
        return this.partnatts;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partnatts</code>.
     */
    public void setPartnatts(Short partnatts) {
        this.partnatts = partnatts;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partdefid</code>.
     */
    public Long getPartdefid() {
        return this.partdefid;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partdefid</code>.
     */
    public void setPartdefid(Long partdefid) {
        this.partdefid = partdefid;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partattrs</code>.
     */
    public Object[] getPartattrs() {
        return this.partattrs;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partattrs</code>.
     */
    public void setPartattrs(Object[] partattrs) {
        this.partattrs = partattrs;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partclass</code>.
     */
    public Object[] getPartclass() {
        return this.partclass;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partclass</code>.
     */
    public void setPartclass(Object[] partclass) {
        this.partclass = partclass;
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partcollation</code>.
     */
    public Object[] getPartcollation() {
        return this.partcollation;
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partcollation</code>.
     */
    public void setPartcollation(Object[] partcollation) {
        this.partcollation = partcollation;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getPartexprs() {
        return this.partexprs;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setPartexprs(Object partexprs) {
        this.partexprs = partexprs;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgPartitionedTable other = (PgPartitionedTable) obj;
        if (this.partrelid == null) {
            if (other.partrelid != null)
                return false;
        }
        else if (!this.partrelid.equals(other.partrelid))
            return false;
        if (this.partstrat == null) {
            if (other.partstrat != null)
                return false;
        }
        else if (!this.partstrat.equals(other.partstrat))
            return false;
        if (this.partnatts == null) {
            if (other.partnatts != null)
                return false;
        }
        else if (!this.partnatts.equals(other.partnatts))
            return false;
        if (this.partdefid == null) {
            if (other.partdefid != null)
                return false;
        }
        else if (!this.partdefid.equals(other.partdefid))
            return false;
        if (this.partattrs == null) {
            if (other.partattrs != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.partattrs, other.partattrs))
            return false;
        if (this.partclass == null) {
            if (other.partclass != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.partclass, other.partclass))
            return false;
        if (this.partcollation == null) {
            if (other.partcollation != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.partcollation, other.partcollation))
            return false;
        if (this.partexprs == null) {
            if (other.partexprs != null)
                return false;
        }
        else if (!this.partexprs.equals(other.partexprs))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partrelid == null) ? 0 : this.partrelid.hashCode());
        result = prime * result + ((this.partstrat == null) ? 0 : this.partstrat.hashCode());
        result = prime * result + ((this.partnatts == null) ? 0 : this.partnatts.hashCode());
        result = prime * result + ((this.partdefid == null) ? 0 : this.partdefid.hashCode());
        result = prime * result + ((this.partattrs == null) ? 0 : Arrays.deepHashCode(this.partattrs));
        result = prime * result + ((this.partclass == null) ? 0 : Arrays.deepHashCode(this.partclass));
        result = prime * result + ((this.partcollation == null) ? 0 : Arrays.deepHashCode(this.partcollation));
        result = prime * result + ((this.partexprs == null) ? 0 : this.partexprs.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgPartitionedTable (");

        sb.append(partrelid);
        sb.append(", ").append(partstrat);
        sb.append(", ").append(partnatts);
        sb.append(", ").append(partdefid);
        sb.append(", ").append(Arrays.deepToString(partattrs));
        sb.append(", ").append(Arrays.deepToString(partclass));
        sb.append(", ").append(Arrays.deepToString(partcollation));
        sb.append(", ").append(partexprs);

        sb.append(")");
        return sb.toString();
    }
}
