/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatDatabaseConflicts implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long datid;
    private String datname;
    private Long conflTablespace;
    private Long conflLock;
    private Long conflSnapshot;
    private Long conflBufferpin;
    private Long conflDeadlock;

    public PgStatDatabaseConflicts() {}

    public PgStatDatabaseConflicts(PgStatDatabaseConflicts value) {
        this.datid = value.datid;
        this.datname = value.datname;
        this.conflTablespace = value.conflTablespace;
        this.conflLock = value.conflLock;
        this.conflSnapshot = value.conflSnapshot;
        this.conflBufferpin = value.conflBufferpin;
        this.conflDeadlock = value.conflDeadlock;
    }

    public PgStatDatabaseConflicts(
        Long datid,
        String datname,
        Long conflTablespace,
        Long conflLock,
        Long conflSnapshot,
        Long conflBufferpin,
        Long conflDeadlock
    ) {
        this.datid = datid;
        this.datname = datname;
        this.conflTablespace = conflTablespace;
        this.conflLock = conflLock;
        this.conflSnapshot = conflSnapshot;
        this.conflBufferpin = conflBufferpin;
        this.conflDeadlock = conflDeadlock;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_database_conflicts.datid</code>.
     */
    public Long getDatid() {
        return this.datid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_database_conflicts.datid</code>.
     */
    public void setDatid(Long datid) {
        this.datid = datid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_database_conflicts.datname</code>.
     */
    public String getDatname() {
        return this.datname;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_database_conflicts.datname</code>.
     */
    public void setDatname(String datname) {
        this.datname = datname;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_tablespace</code>.
     */
    public Long getConflTablespace() {
        return this.conflTablespace;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_tablespace</code>.
     */
    public void setConflTablespace(Long conflTablespace) {
        this.conflTablespace = conflTablespace;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_database_conflicts.confl_lock</code>.
     */
    public Long getConflLock() {
        return this.conflLock;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_database_conflicts.confl_lock</code>.
     */
    public void setConflLock(Long conflLock) {
        this.conflLock = conflLock;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_snapshot</code>.
     */
    public Long getConflSnapshot() {
        return this.conflSnapshot;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_snapshot</code>.
     */
    public void setConflSnapshot(Long conflSnapshot) {
        this.conflSnapshot = conflSnapshot;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_bufferpin</code>.
     */
    public Long getConflBufferpin() {
        return this.conflBufferpin;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_bufferpin</code>.
     */
    public void setConflBufferpin(Long conflBufferpin) {
        this.conflBufferpin = conflBufferpin;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_deadlock</code>.
     */
    public Long getConflDeadlock() {
        return this.conflDeadlock;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_database_conflicts.confl_deadlock</code>.
     */
    public void setConflDeadlock(Long conflDeadlock) {
        this.conflDeadlock = conflDeadlock;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatDatabaseConflicts other = (PgStatDatabaseConflicts) obj;
        if (this.datid == null) {
            if (other.datid != null)
                return false;
        }
        else if (!this.datid.equals(other.datid))
            return false;
        if (this.datname == null) {
            if (other.datname != null)
                return false;
        }
        else if (!this.datname.equals(other.datname))
            return false;
        if (this.conflTablespace == null) {
            if (other.conflTablespace != null)
                return false;
        }
        else if (!this.conflTablespace.equals(other.conflTablespace))
            return false;
        if (this.conflLock == null) {
            if (other.conflLock != null)
                return false;
        }
        else if (!this.conflLock.equals(other.conflLock))
            return false;
        if (this.conflSnapshot == null) {
            if (other.conflSnapshot != null)
                return false;
        }
        else if (!this.conflSnapshot.equals(other.conflSnapshot))
            return false;
        if (this.conflBufferpin == null) {
            if (other.conflBufferpin != null)
                return false;
        }
        else if (!this.conflBufferpin.equals(other.conflBufferpin))
            return false;
        if (this.conflDeadlock == null) {
            if (other.conflDeadlock != null)
                return false;
        }
        else if (!this.conflDeadlock.equals(other.conflDeadlock))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.datid == null) ? 0 : this.datid.hashCode());
        result = prime * result + ((this.datname == null) ? 0 : this.datname.hashCode());
        result = prime * result + ((this.conflTablespace == null) ? 0 : this.conflTablespace.hashCode());
        result = prime * result + ((this.conflLock == null) ? 0 : this.conflLock.hashCode());
        result = prime * result + ((this.conflSnapshot == null) ? 0 : this.conflSnapshot.hashCode());
        result = prime * result + ((this.conflBufferpin == null) ? 0 : this.conflBufferpin.hashCode());
        result = prime * result + ((this.conflDeadlock == null) ? 0 : this.conflDeadlock.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatDatabaseConflicts (");

        sb.append(datid);
        sb.append(", ").append(datname);
        sb.append(", ").append(conflTablespace);
        sb.append(", ").append(conflLock);
        sb.append(", ").append(conflSnapshot);
        sb.append(", ").append(conflBufferpin);
        sb.append(", ").append(conflDeadlock);

        sb.append(")");
        return sb.toString();
    }
}
