/*
 * This file is generated by jOOQ.
 */
package model.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatActivity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long datid;
    private String datname;
    private Integer pid;
    private Integer leaderPid;
    private Long usesysid;
    private String usename;
    private String applicationName;
    private Object clientAddr;
    private String clientHostname;
    private Integer clientPort;
    private OffsetDateTime backendStart;
    private OffsetDateTime xactStart;
    private OffsetDateTime queryStart;
    private OffsetDateTime stateChange;
    private String waitEventType;
    private String waitEvent;
    private String state;
    private Long backendXid;
    private Long backendXmin;
    private Long queryId;
    private String query;
    private String backendType;

    public PgStatActivity() {}

    public PgStatActivity(PgStatActivity value) {
        this.datid = value.datid;
        this.datname = value.datname;
        this.pid = value.pid;
        this.leaderPid = value.leaderPid;
        this.usesysid = value.usesysid;
        this.usename = value.usename;
        this.applicationName = value.applicationName;
        this.clientAddr = value.clientAddr;
        this.clientHostname = value.clientHostname;
        this.clientPort = value.clientPort;
        this.backendStart = value.backendStart;
        this.xactStart = value.xactStart;
        this.queryStart = value.queryStart;
        this.stateChange = value.stateChange;
        this.waitEventType = value.waitEventType;
        this.waitEvent = value.waitEvent;
        this.state = value.state;
        this.backendXid = value.backendXid;
        this.backendXmin = value.backendXmin;
        this.queryId = value.queryId;
        this.query = value.query;
        this.backendType = value.backendType;
    }

    public PgStatActivity(
        Long datid,
        String datname,
        Integer pid,
        Integer leaderPid,
        Long usesysid,
        String usename,
        String applicationName,
        Object clientAddr,
        String clientHostname,
        Integer clientPort,
        OffsetDateTime backendStart,
        OffsetDateTime xactStart,
        OffsetDateTime queryStart,
        OffsetDateTime stateChange,
        String waitEventType,
        String waitEvent,
        String state,
        Long backendXid,
        Long backendXmin,
        Long queryId,
        String query,
        String backendType
    ) {
        this.datid = datid;
        this.datname = datname;
        this.pid = pid;
        this.leaderPid = leaderPid;
        this.usesysid = usesysid;
        this.usename = usename;
        this.applicationName = applicationName;
        this.clientAddr = clientAddr;
        this.clientHostname = clientHostname;
        this.clientPort = clientPort;
        this.backendStart = backendStart;
        this.xactStart = xactStart;
        this.queryStart = queryStart;
        this.stateChange = stateChange;
        this.waitEventType = waitEventType;
        this.waitEvent = waitEvent;
        this.state = state;
        this.backendXid = backendXid;
        this.backendXmin = backendXmin;
        this.queryId = queryId;
        this.query = query;
        this.backendType = backendType;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.datid</code>.
     */
    public Long getDatid() {
        return this.datid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.datid</code>.
     */
    public void setDatid(Long datid) {
        this.datid = datid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.datname</code>.
     */
    public String getDatname() {
        return this.datname;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.datname</code>.
     */
    public void setDatname(String datname) {
        this.datname = datname;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.pid</code>.
     */
    public Integer getPid() {
        return this.pid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.pid</code>.
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.leader_pid</code>.
     */
    public Integer getLeaderPid() {
        return this.leaderPid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.leader_pid</code>.
     */
    public void setLeaderPid(Integer leaderPid) {
        this.leaderPid = leaderPid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.usesysid</code>.
     */
    public Long getUsesysid() {
        return this.usesysid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.usesysid</code>.
     */
    public void setUsesysid(Long usesysid) {
        this.usesysid = usesysid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.usename</code>.
     */
    public String getUsename() {
        return this.usename;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.usename</code>.
     */
    public void setUsename(String usename) {
        this.usename = usename;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.application_name</code>.
     */
    public String getApplicationName() {
        return this.applicationName;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.application_name</code>.
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getClientAddr() {
        return this.clientAddr;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setClientAddr(Object clientAddr) {
        this.clientAddr = clientAddr;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.client_hostname</code>.
     */
    public String getClientHostname() {
        return this.clientHostname;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.client_hostname</code>.
     */
    public void setClientHostname(String clientHostname) {
        this.clientHostname = clientHostname;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.client_port</code>.
     */
    public Integer getClientPort() {
        return this.clientPort;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.client_port</code>.
     */
    public void setClientPort(Integer clientPort) {
        this.clientPort = clientPort;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_start</code>.
     */
    public OffsetDateTime getBackendStart() {
        return this.backendStart;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_start</code>.
     */
    public void setBackendStart(OffsetDateTime backendStart) {
        this.backendStart = backendStart;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.xact_start</code>.
     */
    public OffsetDateTime getXactStart() {
        return this.xactStart;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.xact_start</code>.
     */
    public void setXactStart(OffsetDateTime xactStart) {
        this.xactStart = xactStart;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.query_start</code>.
     */
    public OffsetDateTime getQueryStart() {
        return this.queryStart;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.query_start</code>.
     */
    public void setQueryStart(OffsetDateTime queryStart) {
        this.queryStart = queryStart;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.state_change</code>.
     */
    public OffsetDateTime getStateChange() {
        return this.stateChange;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.state_change</code>.
     */
    public void setStateChange(OffsetDateTime stateChange) {
        this.stateChange = stateChange;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.wait_event_type</code>.
     */
    public String getWaitEventType() {
        return this.waitEventType;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.wait_event_type</code>.
     */
    public void setWaitEventType(String waitEventType) {
        this.waitEventType = waitEventType;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.wait_event</code>.
     */
    public String getWaitEvent() {
        return this.waitEvent;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.wait_event</code>.
     */
    public void setWaitEvent(String waitEvent) {
        this.waitEvent = waitEvent;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.state</code>.
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_xid</code>.
     */
    public Long getBackendXid() {
        return this.backendXid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_xid</code>.
     */
    public void setBackendXid(Long backendXid) {
        this.backendXid = backendXid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_xmin</code>.
     */
    public Long getBackendXmin() {
        return this.backendXmin;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_xmin</code>.
     */
    public void setBackendXmin(Long backendXmin) {
        this.backendXmin = backendXmin;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.query_id</code>.
     */
    public Long getQueryId() {
        return this.queryId;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.query_id</code>.
     */
    public void setQueryId(Long queryId) {
        this.queryId = queryId;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.query</code>.
     */
    public String getQuery() {
        return this.query;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.query</code>.
     */
    public void setQuery(String query) {
        this.query = query;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_type</code>.
     */
    public String getBackendType() {
        return this.backendType;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_type</code>.
     */
    public void setBackendType(String backendType) {
        this.backendType = backendType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatActivity other = (PgStatActivity) obj;
        if (this.datid == null) {
            if (other.datid != null)
                return false;
        }
        else if (!this.datid.equals(other.datid))
            return false;
        if (this.datname == null) {
            if (other.datname != null)
                return false;
        }
        else if (!this.datname.equals(other.datname))
            return false;
        if (this.pid == null) {
            if (other.pid != null)
                return false;
        }
        else if (!this.pid.equals(other.pid))
            return false;
        if (this.leaderPid == null) {
            if (other.leaderPid != null)
                return false;
        }
        else if (!this.leaderPid.equals(other.leaderPid))
            return false;
        if (this.usesysid == null) {
            if (other.usesysid != null)
                return false;
        }
        else if (!this.usesysid.equals(other.usesysid))
            return false;
        if (this.usename == null) {
            if (other.usename != null)
                return false;
        }
        else if (!this.usename.equals(other.usename))
            return false;
        if (this.applicationName == null) {
            if (other.applicationName != null)
                return false;
        }
        else if (!this.applicationName.equals(other.applicationName))
            return false;
        if (this.clientAddr == null) {
            if (other.clientAddr != null)
                return false;
        }
        else if (!this.clientAddr.equals(other.clientAddr))
            return false;
        if (this.clientHostname == null) {
            if (other.clientHostname != null)
                return false;
        }
        else if (!this.clientHostname.equals(other.clientHostname))
            return false;
        if (this.clientPort == null) {
            if (other.clientPort != null)
                return false;
        }
        else if (!this.clientPort.equals(other.clientPort))
            return false;
        if (this.backendStart == null) {
            if (other.backendStart != null)
                return false;
        }
        else if (!this.backendStart.equals(other.backendStart))
            return false;
        if (this.xactStart == null) {
            if (other.xactStart != null)
                return false;
        }
        else if (!this.xactStart.equals(other.xactStart))
            return false;
        if (this.queryStart == null) {
            if (other.queryStart != null)
                return false;
        }
        else if (!this.queryStart.equals(other.queryStart))
            return false;
        if (this.stateChange == null) {
            if (other.stateChange != null)
                return false;
        }
        else if (!this.stateChange.equals(other.stateChange))
            return false;
        if (this.waitEventType == null) {
            if (other.waitEventType != null)
                return false;
        }
        else if (!this.waitEventType.equals(other.waitEventType))
            return false;
        if (this.waitEvent == null) {
            if (other.waitEvent != null)
                return false;
        }
        else if (!this.waitEvent.equals(other.waitEvent))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.backendXid == null) {
            if (other.backendXid != null)
                return false;
        }
        else if (!this.backendXid.equals(other.backendXid))
            return false;
        if (this.backendXmin == null) {
            if (other.backendXmin != null)
                return false;
        }
        else if (!this.backendXmin.equals(other.backendXmin))
            return false;
        if (this.queryId == null) {
            if (other.queryId != null)
                return false;
        }
        else if (!this.queryId.equals(other.queryId))
            return false;
        if (this.query == null) {
            if (other.query != null)
                return false;
        }
        else if (!this.query.equals(other.query))
            return false;
        if (this.backendType == null) {
            if (other.backendType != null)
                return false;
        }
        else if (!this.backendType.equals(other.backendType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.datid == null) ? 0 : this.datid.hashCode());
        result = prime * result + ((this.datname == null) ? 0 : this.datname.hashCode());
        result = prime * result + ((this.pid == null) ? 0 : this.pid.hashCode());
        result = prime * result + ((this.leaderPid == null) ? 0 : this.leaderPid.hashCode());
        result = prime * result + ((this.usesysid == null) ? 0 : this.usesysid.hashCode());
        result = prime * result + ((this.usename == null) ? 0 : this.usename.hashCode());
        result = prime * result + ((this.applicationName == null) ? 0 : this.applicationName.hashCode());
        result = prime * result + ((this.clientAddr == null) ? 0 : this.clientAddr.hashCode());
        result = prime * result + ((this.clientHostname == null) ? 0 : this.clientHostname.hashCode());
        result = prime * result + ((this.clientPort == null) ? 0 : this.clientPort.hashCode());
        result = prime * result + ((this.backendStart == null) ? 0 : this.backendStart.hashCode());
        result = prime * result + ((this.xactStart == null) ? 0 : this.xactStart.hashCode());
        result = prime * result + ((this.queryStart == null) ? 0 : this.queryStart.hashCode());
        result = prime * result + ((this.stateChange == null) ? 0 : this.stateChange.hashCode());
        result = prime * result + ((this.waitEventType == null) ? 0 : this.waitEventType.hashCode());
        result = prime * result + ((this.waitEvent == null) ? 0 : this.waitEvent.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.backendXid == null) ? 0 : this.backendXid.hashCode());
        result = prime * result + ((this.backendXmin == null) ? 0 : this.backendXmin.hashCode());
        result = prime * result + ((this.queryId == null) ? 0 : this.queryId.hashCode());
        result = prime * result + ((this.query == null) ? 0 : this.query.hashCode());
        result = prime * result + ((this.backendType == null) ? 0 : this.backendType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatActivity (");

        sb.append(datid);
        sb.append(", ").append(datname);
        sb.append(", ").append(pid);
        sb.append(", ").append(leaderPid);
        sb.append(", ").append(usesysid);
        sb.append(", ").append(usename);
        sb.append(", ").append(applicationName);
        sb.append(", ").append(clientAddr);
        sb.append(", ").append(clientHostname);
        sb.append(", ").append(clientPort);
        sb.append(", ").append(backendStart);
        sb.append(", ").append(xactStart);
        sb.append(", ").append(queryStart);
        sb.append(", ").append(stateChange);
        sb.append(", ").append(waitEventType);
        sb.append(", ").append(waitEvent);
        sb.append(", ").append(state);
        sb.append(", ").append(backendXid);
        sb.append(", ").append(backendXmin);
        sb.append(", ").append(queryId);
        sb.append(", ").append(query);
        sb.append(", ").append(backendType);

        sb.append(")");
        return sb.toString();
    }
}
