/*
 * This file is generated by jOOQ.
 */
package model.company;


import java.util.Arrays;
import java.util.List;

import model.DefaultCatalog;
import model.company.tables.Customers;
import model.company.tables.Employees;
import model.company.tables.Offices;
import model.company.tables.Orderdetails;
import model.company.tables.Orders;
import model.company.tables.Payments;
import model.company.tables.Productlines;
import model.company.tables.Products;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>company</code>
     */
    public static final Company COMPANY = new Company();

    /**
     * The table <code>company.customers</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>company.employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>company.offices</code>.
     */
    public final Offices OFFICES = Offices.OFFICES;

    /**
     * The table <code>company.orderdetails</code>.
     */
    public final Orderdetails ORDERDETAILS = Orderdetails.ORDERDETAILS;

    /**
     * The table <code>company.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>company.payments</code>.
     */
    public final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>company.productlines</code>.
     */
    public final Productlines PRODUCTLINES = Productlines.PRODUCTLINES;

    /**
     * The table <code>company.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private Company() {
        super("company", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customers.CUSTOMERS,
            Employees.EMPLOYEES,
            Offices.OFFICES,
            Orderdetails.ORDERDETAILS,
            Orders.ORDERS,
            Payments.PAYMENTS,
            Productlines.PRODUCTLINES,
            Products.PRODUCTS
        );
    }
}
