/*
 * This file is generated by jOOQ.
 */
package model.company.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer ordernumber;
    private String productcode;
    private Integer quantityordered;
    private BigDecimal priceeach;
    private Short orderlinenumber;

    public Orderdetails() {}

    public Orderdetails(Orderdetails value) {
        this.ordernumber = value.ordernumber;
        this.productcode = value.productcode;
        this.quantityordered = value.quantityordered;
        this.priceeach = value.priceeach;
        this.orderlinenumber = value.orderlinenumber;
    }

    public Orderdetails(
        Integer ordernumber,
        String productcode,
        Integer quantityordered,
        BigDecimal priceeach,
        Short orderlinenumber
    ) {
        this.ordernumber = ordernumber;
        this.productcode = productcode;
        this.quantityordered = quantityordered;
        this.priceeach = priceeach;
        this.orderlinenumber = orderlinenumber;
    }

    /**
     * Getter for <code>company.orderdetails.ordernumber</code>.
     */
    public Integer getOrdernumber() {
        return this.ordernumber;
    }

    /**
     * Setter for <code>company.orderdetails.ordernumber</code>.
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * Getter for <code>company.orderdetails.productcode</code>.
     */
    public String getProductcode() {
        return this.productcode;
    }

    /**
     * Setter for <code>company.orderdetails.productcode</code>.
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * Getter for <code>company.orderdetails.quantityordered</code>.
     */
    public Integer getQuantityordered() {
        return this.quantityordered;
    }

    /**
     * Setter for <code>company.orderdetails.quantityordered</code>.
     */
    public void setQuantityordered(Integer quantityordered) {
        this.quantityordered = quantityordered;
    }

    /**
     * Getter for <code>company.orderdetails.priceeach</code>.
     */
    public BigDecimal getPriceeach() {
        return this.priceeach;
    }

    /**
     * Setter for <code>company.orderdetails.priceeach</code>.
     */
    public void setPriceeach(BigDecimal priceeach) {
        this.priceeach = priceeach;
    }

    /**
     * Getter for <code>company.orderdetails.orderlinenumber</code>.
     */
    public Short getOrderlinenumber() {
        return this.orderlinenumber;
    }

    /**
     * Setter for <code>company.orderdetails.orderlinenumber</code>.
     */
    public void setOrderlinenumber(Short orderlinenumber) {
        this.orderlinenumber = orderlinenumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Orderdetails other = (Orderdetails) obj;
        if (this.ordernumber == null) {
            if (other.ordernumber != null)
                return false;
        }
        else if (!this.ordernumber.equals(other.ordernumber))
            return false;
        if (this.productcode == null) {
            if (other.productcode != null)
                return false;
        }
        else if (!this.productcode.equals(other.productcode))
            return false;
        if (this.quantityordered == null) {
            if (other.quantityordered != null)
                return false;
        }
        else if (!this.quantityordered.equals(other.quantityordered))
            return false;
        if (this.priceeach == null) {
            if (other.priceeach != null)
                return false;
        }
        else if (!this.priceeach.equals(other.priceeach))
            return false;
        if (this.orderlinenumber == null) {
            if (other.orderlinenumber != null)
                return false;
        }
        else if (!this.orderlinenumber.equals(other.orderlinenumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ordernumber == null) ? 0 : this.ordernumber.hashCode());
        result = prime * result + ((this.productcode == null) ? 0 : this.productcode.hashCode());
        result = prime * result + ((this.quantityordered == null) ? 0 : this.quantityordered.hashCode());
        result = prime * result + ((this.priceeach == null) ? 0 : this.priceeach.hashCode());
        result = prime * result + ((this.orderlinenumber == null) ? 0 : this.orderlinenumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orderdetails (");

        sb.append(ordernumber);
        sb.append(", ").append(productcode);
        sb.append(", ").append(quantityordered);
        sb.append(", ").append(priceeach);
        sb.append(", ").append(orderlinenumber);

        sb.append(")");
        return sb.toString();
    }
}
