/*
 * This file is generated by jOOQ.
 */
package model.company.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products implements Serializable {

    private static final long serialVersionUID = 1L;

    private String productcode;
    private String productline;
    private String productname;
    private String productscale;
    private String productvendor;
    private String productdescription;
    private Short quantityinstock;
    private BigDecimal buyprice;
    private BigDecimal msrp;

    public Products() {}

    public Products(Products value) {
        this.productcode = value.productcode;
        this.productline = value.productline;
        this.productname = value.productname;
        this.productscale = value.productscale;
        this.productvendor = value.productvendor;
        this.productdescription = value.productdescription;
        this.quantityinstock = value.quantityinstock;
        this.buyprice = value.buyprice;
        this.msrp = value.msrp;
    }

    public Products(
        String productcode,
        String productline,
        String productname,
        String productscale,
        String productvendor,
        String productdescription,
        Short quantityinstock,
        BigDecimal buyprice,
        BigDecimal msrp
    ) {
        this.productcode = productcode;
        this.productline = productline;
        this.productname = productname;
        this.productscale = productscale;
        this.productvendor = productvendor;
        this.productdescription = productdescription;
        this.quantityinstock = quantityinstock;
        this.buyprice = buyprice;
        this.msrp = msrp;
    }

    /**
     * Getter for <code>company.products.productcode</code>.
     */
    public String getProductcode() {
        return this.productcode;
    }

    /**
     * Setter for <code>company.products.productcode</code>.
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * Getter for <code>company.products.productline</code>.
     */
    public String getProductline() {
        return this.productline;
    }

    /**
     * Setter for <code>company.products.productline</code>.
     */
    public void setProductline(String productline) {
        this.productline = productline;
    }

    /**
     * Getter for <code>company.products.productname</code>.
     */
    public String getProductname() {
        return this.productname;
    }

    /**
     * Setter for <code>company.products.productname</code>.
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * Getter for <code>company.products.productscale</code>.
     */
    public String getProductscale() {
        return this.productscale;
    }

    /**
     * Setter for <code>company.products.productscale</code>.
     */
    public void setProductscale(String productscale) {
        this.productscale = productscale;
    }

    /**
     * Getter for <code>company.products.productvendor</code>.
     */
    public String getProductvendor() {
        return this.productvendor;
    }

    /**
     * Setter for <code>company.products.productvendor</code>.
     */
    public void setProductvendor(String productvendor) {
        this.productvendor = productvendor;
    }

    /**
     * Getter for <code>company.products.productdescription</code>.
     */
    public String getProductdescription() {
        return this.productdescription;
    }

    /**
     * Setter for <code>company.products.productdescription</code>.
     */
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    /**
     * Getter for <code>company.products.quantityinstock</code>.
     */
    public Short getQuantityinstock() {
        return this.quantityinstock;
    }

    /**
     * Setter for <code>company.products.quantityinstock</code>.
     */
    public void setQuantityinstock(Short quantityinstock) {
        this.quantityinstock = quantityinstock;
    }

    /**
     * Getter for <code>company.products.buyprice</code>.
     */
    public BigDecimal getBuyprice() {
        return this.buyprice;
    }

    /**
     * Setter for <code>company.products.buyprice</code>.
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * Getter for <code>company.products.msrp</code>.
     */
    public BigDecimal getMsrp() {
        return this.msrp;
    }

    /**
     * Setter for <code>company.products.msrp</code>.
     */
    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Products other = (Products) obj;
        if (this.productcode == null) {
            if (other.productcode != null)
                return false;
        }
        else if (!this.productcode.equals(other.productcode))
            return false;
        if (this.productline == null) {
            if (other.productline != null)
                return false;
        }
        else if (!this.productline.equals(other.productline))
            return false;
        if (this.productname == null) {
            if (other.productname != null)
                return false;
        }
        else if (!this.productname.equals(other.productname))
            return false;
        if (this.productscale == null) {
            if (other.productscale != null)
                return false;
        }
        else if (!this.productscale.equals(other.productscale))
            return false;
        if (this.productvendor == null) {
            if (other.productvendor != null)
                return false;
        }
        else if (!this.productvendor.equals(other.productvendor))
            return false;
        if (this.productdescription == null) {
            if (other.productdescription != null)
                return false;
        }
        else if (!this.productdescription.equals(other.productdescription))
            return false;
        if (this.quantityinstock == null) {
            if (other.quantityinstock != null)
                return false;
        }
        else if (!this.quantityinstock.equals(other.quantityinstock))
            return false;
        if (this.buyprice == null) {
            if (other.buyprice != null)
                return false;
        }
        else if (!this.buyprice.equals(other.buyprice))
            return false;
        if (this.msrp == null) {
            if (other.msrp != null)
                return false;
        }
        else if (!this.msrp.equals(other.msrp))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productcode == null) ? 0 : this.productcode.hashCode());
        result = prime * result + ((this.productline == null) ? 0 : this.productline.hashCode());
        result = prime * result + ((this.productname == null) ? 0 : this.productname.hashCode());
        result = prime * result + ((this.productscale == null) ? 0 : this.productscale.hashCode());
        result = prime * result + ((this.productvendor == null) ? 0 : this.productvendor.hashCode());
        result = prime * result + ((this.productdescription == null) ? 0 : this.productdescription.hashCode());
        result = prime * result + ((this.quantityinstock == null) ? 0 : this.quantityinstock.hashCode());
        result = prime * result + ((this.buyprice == null) ? 0 : this.buyprice.hashCode());
        result = prime * result + ((this.msrp == null) ? 0 : this.msrp.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Products (");

        sb.append(productcode);
        sb.append(", ").append(productline);
        sb.append(", ").append(productname);
        sb.append(", ").append(productscale);
        sb.append(", ").append(productvendor);
        sb.append(", ").append(productdescription);
        sb.append(", ").append(quantityinstock);
        sb.append(", ").append(buyprice);
        sb.append(", ").append(msrp);

        sb.append(")");
        return sb.toString();
    }
}
