/*
 * This file is generated by jOOQ.
 */
package model.information_schema.tables;


import java.util.function.Function;

import model.information_schema.InformationSchema;
import model.information_schema.tables.records.RoutinePrivilegesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutinePrivileges extends TableImpl<RoutinePrivilegesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>information_schema.routine_privileges</code>
     */
    public static final RoutinePrivileges ROUTINE_PRIVILEGES = new RoutinePrivileges();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoutinePrivilegesRecord> getRecordType() {
        return RoutinePrivilegesRecord.class;
    }

    /**
     * The column <code>information_schema.routine_privileges.grantor</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> GRANTOR = createField(DSL.name("grantor"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column <code>information_schema.routine_privileges.grantee</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> GRANTEE = createField(DSL.name("grantee"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.specific_catalog</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> SPECIFIC_CATALOG = createField(DSL.name("specific_catalog"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.specific_schema</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> SPECIFIC_SCHEMA = createField(DSL.name("specific_schema"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.specific_name</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> SPECIFIC_NAME = createField(DSL.name("specific_name"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.routine_catalog</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> ROUTINE_CATALOG = createField(DSL.name("routine_catalog"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.routine_schema</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> ROUTINE_SCHEMA = createField(DSL.name("routine_schema"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.routine_name</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> ROUTINE_NAME = createField(DSL.name("routine_name"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.privilege_type</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> PRIVILEGE_TYPE = createField(DSL.name("privilege_type"), model.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.routine_privileges.is_grantable</code>.
     */
    public final TableField<RoutinePrivilegesRecord, String> IS_GRANTABLE = createField(DSL.name("is_grantable"), model.information_schema.Domains.YES_OR_NO.getDataType(), this, "");

    private RoutinePrivileges(Name alias, Table<RoutinePrivilegesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoutinePrivileges(Name alias, Table<RoutinePrivilegesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>information_schema.routine_privileges</code>
     * table reference
     */
    public RoutinePrivileges(String alias) {
        this(DSL.name(alias), ROUTINE_PRIVILEGES);
    }

    /**
     * Create an aliased <code>information_schema.routine_privileges</code>
     * table reference
     */
    public RoutinePrivileges(Name alias) {
        this(alias, ROUTINE_PRIVILEGES);
    }

    /**
     * Create a <code>information_schema.routine_privileges</code> table
     * reference
     */
    public RoutinePrivileges() {
        this(DSL.name("routine_privileges"), null);
    }

    public <O extends Record> RoutinePrivileges(Table<O> child, ForeignKey<O, RoutinePrivilegesRecord> key) {
        super(child, key, ROUTINE_PRIVILEGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public RoutinePrivileges as(String alias) {
        return new RoutinePrivileges(DSL.name(alias), this);
    }

    @Override
    public RoutinePrivileges as(Name alias) {
        return new RoutinePrivileges(alias, this);
    }

    @Override
    public RoutinePrivileges as(Table<?> alias) {
        return new RoutinePrivileges(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutinePrivileges rename(String name) {
        return new RoutinePrivileges(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutinePrivileges rename(Name name) {
        return new RoutinePrivileges(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutinePrivileges rename(Table<?> name) {
        return new RoutinePrivileges(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
