/*
 * This file is generated by jOOQ.
 */
package model.information_schema.tables;


import java.util.function.Function;

import model.information_schema.InformationSchema;
import model.information_schema.tables.records.ViewTableUsageRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableUsage extends TableImpl<ViewTableUsageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>information_schema.view_table_usage</code>
     */
    public static final ViewTableUsage VIEW_TABLE_USAGE = new ViewTableUsage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewTableUsageRecord> getRecordType() {
        return ViewTableUsageRecord.class;
    }

    /**
     * The column <code>information_schema.view_table_usage.view_catalog</code>.
     */
    public final TableField<ViewTableUsageRecord, String> VIEW_CATALOG = createField(DSL.name("view_catalog"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column <code>information_schema.view_table_usage.view_schema</code>.
     */
    public final TableField<ViewTableUsageRecord, String> VIEW_SCHEMA = createField(DSL.name("view_schema"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column <code>information_schema.view_table_usage.view_name</code>.
     */
    public final TableField<ViewTableUsageRecord, String> VIEW_NAME = createField(DSL.name("view_name"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.view_table_usage.table_catalog</code>.
     */
    public final TableField<ViewTableUsageRecord, String> TABLE_CATALOG = createField(DSL.name("table_catalog"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column <code>information_schema.view_table_usage.table_schema</code>.
     */
    public final TableField<ViewTableUsageRecord, String> TABLE_SCHEMA = createField(DSL.name("table_schema"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column <code>information_schema.view_table_usage.table_name</code>.
     */
    public final TableField<ViewTableUsageRecord, String> TABLE_NAME = createField(DSL.name("table_name"), model.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    private ViewTableUsage(Name alias, Table<ViewTableUsageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewTableUsage(Name alias, Table<ViewTableUsageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>information_schema.view_table_usage</code> table
     * reference
     */
    public ViewTableUsage(String alias) {
        this(DSL.name(alias), VIEW_TABLE_USAGE);
    }

    /**
     * Create an aliased <code>information_schema.view_table_usage</code> table
     * reference
     */
    public ViewTableUsage(Name alias) {
        this(alias, VIEW_TABLE_USAGE);
    }

    /**
     * Create a <code>information_schema.view_table_usage</code> table reference
     */
    public ViewTableUsage() {
        this(DSL.name("view_table_usage"), null);
    }

    public <O extends Record> ViewTableUsage(Table<O> child, ForeignKey<O, ViewTableUsageRecord> key) {
        super(child, key, VIEW_TABLE_USAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public ViewTableUsage as(String alias) {
        return new ViewTableUsage(DSL.name(alias), this);
    }

    @Override
    public ViewTableUsage as(Name alias) {
        return new ViewTableUsage(alias, this);
    }

    @Override
    public ViewTableUsage as(Table<?> alias) {
        return new ViewTableUsage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsage rename(String name) {
        return new ViewTableUsage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsage rename(Name name) {
        return new ViewTableUsage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsage rename(Table<?> name) {
        return new ViewTableUsage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
